server:
  port: 8080

spring:
  datasource:
    url: ${URL_DATABASE}
    password: ${URL_PASSWORD}
    username: ${URL_USERNAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


URL_DATABASE: jdbc:mysql://localhost:3306/DB?serverTimeZone=UTC
URL_USERNAME: root
URL_PASSWORD: